<?php
$data = array (
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '中药养生',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '4',
    'name' => '中药养生',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '个人护理',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '1',
    'name' => '个人护理',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '医疗器械',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => '医疗器械',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '母婴专场',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '母婴专场',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '营养保健',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '2',
    'name' => '营养保健',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '健康体检',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '9',
    'name' => '健康体检',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '中西药品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '中西药品',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '食品百货',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '3',
    'name' => '食品百货',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '海外精选',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '海外精选',
  ),
);
?>